workflows:
  android-workflow:
    name: Continental APK
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.continental.app"
      android_signing:
        - keystore_reference
      groups:
        - keystore_credentials
      java: 17

    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build debug APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
